### ISSUE TITLE
TODO: refactor UX component templates down

### ISSUE THREAD

**Issue by ghost** [p2peace/twister-renyan#1]
Will add more as I find them.
- [ ] post-area
- [ ] modal/prompt/confirm wrappers
- [ ] postboards
- [ ] profile-info/profile-cards
- [ ] navbars
- [ ] secret key import fields
